sudo: required
language: node_js
node_js:
- '8'
env:
  global:
    - CC_TEST_REPORTER_ID=6acf2ebc499578d84eb70d6e0758f702491c64598017dedd659974a6e29876b3
before_install:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
before_script:
  - npm install -g grunt grunt-cli
script: npm test
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
- grunt coveralls
